name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Rust target
      run: rustup target add riscv64imac-unknown-none-elf
    - name: Install tools
      run: make install-tools
    - name: Run integration
      run: cargo test
